### ISSUE TITLE
The first-connected client doesn't receive new child document if updated both child and parent documents

### ISSUE THREAD

**Issue by davidyuk** [Meteor-Community-Packages/meteor-publish-composite#110]
Hi!
Code in my app looks like this:
```
publishComposite('test', () => [{
  find: () => Collection1.find({}),
  children: [{
    // of course, in my app this cursor depends on document from Collection1
    find: () => Collection2.find({}),
  }],
}]);

Meteor.methods({
  'test': () => {
    c += 1;
    Collection1.update({}, { $set: { counter: c } });
    Collection2.update({}, { $set: { counter: c } });
  },
});
```
So, after somebody call the method, the client what were connected first will stay with old child document value.
I have prepared the reproduction repository: https://github.com/Davidyuk/meteor-publish-composite-issue. You need to open it in several browser instances and click `Run method` button. Then you should see that in one of browser instances counters will become unsynced.

**Comment by StorytellerCZ** [comment]
Fixed in #133
