### ISSUE TITLE
Declaration file for TypeScript

### ISSUE THREAD

**Issue by Rechdan** [Meteor-Community-Packages/meteor-publish-composite#131]
So, I'm using TypeScript and I saw that there wasn't any declaration files, so I made one super fast, first time using this module so I'm not sure what to declare, if anyone has a better solution please let me know! 😁

```ts
declare module 'meteor/reywood:publish-composite' {
	import { Mongo } from 'meteor/mongo';

	interface IOptions {
		find: <T = any>() => Mongo.Cursor<T>;
		children?: IOptions[];
		collectionName?: string;
	}

	function publishComposite(name: string, options: IOptions): void;
}
```

**Comment by ruohki** [comment]
These are not correct if you want to use parameters

**Comment by timsun28** [comment]
Hi, 
I'm trying to add my own types to this package as well, but I can't seem to get the find function working properly. 
I've kept the following:
```ts
interface IOptions {
        find: <T = any>() => Mongo.Cursor<T>;
        children?: IOptions[];
        collectionName?: string;
}
function publishComposite(name: string, options: (this: Subscription, dataSpecs: any) => IOptions): void;
```

Where dataSpecs is my own parameter with the queries etc. 

The function will return an IOptions with the find function that returns a Mongo.Cursor. 

In my publication file I have the following example code:

```ts
publishComposite("myPublication", function (dataSpecs: any) {
    check(dataSpecs, Object);
    return {
        find() {
            const query: Mongo.Selector<MyCollection> = {
                ...dataSpecs.template.query,
                author: this.userId ?? "",
            };
            return Collection.find(query, dataSpecs.template.props);
        }
    }
});
```

Here I have the MyCollection as type for my collection and the Collection.find() returns a Mongo.Cursor<MyCollection, any>
But typescript returns the following error:
Type '<T = any>() => Cursor<MyCollection, any>' is not assignable to type '<T = any>() => Cursor<T, T>'.

Could anyone explain how this could be solved as I couldn't find a clear answer on the internet. 

In case I get this solved, I will be happy to share my .d.ts file here and get it added to the package for others to use as well. 

Thank you in advance!

**Comment by StorytellerCZ** [comment]
PRs welcome!

**Comment by timsun28** [comment]
For anyone who would like to use my code, feel free to use it as a start. 
I'm not using this package any more in my projects and I don't have a lot of time right now to help out, but will check back later if there has been any progress on this.

**Comment by StorytellerCZ** [comment]
Added this in v1.8.4, not perfect but a start.
