### ISSUE TITLE
Remove underscore

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/meteor-publish-composite#158]
Good first issue for [Hacktoberfest](https://hacktoberfest.com/). Remove the need for `underscore` package.

Good reference:
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

**Comment by Nandika-A** [comment]
Hello! I am a beginner. Can I contribute to this issue?

**Comment by StorytellerCZ** [comment]
@Nandika-A sure, go ahead. Where possible please replace underscore references with native one. See: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore for reference. If there currently isn't a native version for the underscore function, skip it for now. Focus on your first PR to just be the easy ones. Then once you have a PR for that you can tackle the remaining underscore functions which will require either implementing our own version of the code or getting a package to do that, but best if that is in another PR so that we can review it faster.

**Comment by Nandika-A** [comment]
I have replaced all the underscore references whose native versions are available in PR 161. Please let me know if any changes are required.

**Comment by Rahulkottak** [comment]
Can I try solving this issue as I'm new too!

**Comment by StorytellerCZ** [comment]
Yes, the initial easy part has been done by @Nandika-A, so now it is to figure out how to replace functions that hat don't have native equivalent. If the function is easy enough, we could probably create a utilities file with them and just have them in the package or we could import a package that has just that function as lodash I believe is now split into these tiny one function packages.

**Comment by Nandika-A** [comment]
@StorytellerCZ should I do the rest part also? Underscore is remaining in _.any() and _.isEqual(), which I had skipped earlier as their natives aren't available.

**Comment by Rahulkottak** [comment]
@Nandika-A hnhn sure you can go for it.. its not like asking every time for contribution... Just code well and send PR

**Comment by reywood** [comment]
> @StorytellerCZ should I do the rest part also? Underscore is remaining in _.any() and _.isEqual(), which I had skipped earlier as their natives aren't available.

I believe [`Array.some`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) can replace `_.any`

**Comment by Nandika-A** [comment]
Yes, @reywood! And there are alternatives to _.isEqual() like JSON.stringify() and deep-equal, but they have some limitations. So should we import another package for this or create a utilities file?

**Comment by Nandika-A** [comment]
Hello @StorytellerCZ! The function _.isEqual() has its definition in [lodash.isequal](https://www.npmjs.com/package/lodash.isequal?activeTab=code). Should I create a utilities file for this?

**Comment by StorytellerCZ** [comment]
That one looks big enough to be worthwhile to import as package.

**Comment by Nandika-A** [comment]
So should I import it as a Node.js module?

**Comment by StorytellerCZ** [comment]
Yes, do you know how to do it for packages?

**Comment by Nandika-A** [comment]
> Yes, do you know how to do it for packages?

Yes, it is mentioned in the documentation." npm i lodash.isequal" will import '_.isEqual' as a module.

**Comment by Nandika-A** [comment]
I have replaced the remaining methods in PR #162 and installed lodash.isequal in node-modules. Please let me know if any changes are required.
