### ISSUE TITLE
Create GitHub action to run tests

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/meteor-publish-composite#159]
Check out other repositories in the organization and setup GitHub action to run tests on pushes and PRs.

**Comment by vinayakhegde1** [comment]
@StorytellerCZ Hello I'm new to open source and git&github aswell . I checked the meteor-collection2 testsuite.yml file I wanted to know whether I have to create the same action file or i have to make any changes for this repo.Sorry for asking silly doubts but I'm curious to know

**Comment by dpatte** [comment]
I am heading from Ottawa to Mississauga for Thursday late afternoon, and will be in the area until after thanksgiving.


----- Original Message -----
