### ISSUE TITLE
Error: Doc not found in list

### ISSUE THREAD

**Issue by dnish** [Meteor-Community-Packages/meteor-publish-composite#167]
Hey,
after upgrading from 1.7.3 to 1.8.2 our app stops working. We receive the following error on the server side:

```
(STDERR) (node:3010) UnhandledPromiseRejectionWarning: Error: Doc not found in list: 3831bc8e8a7dfeb7b12e4f1d480a0faf
(STDERR) at PublishedDocumentList.addChildPub (packages/reywood:publish-composite/lib/published_document_list.js:25:13)
```

In our case we use FastRender with SSR to receive the subscription data. So we have something like this in our main.js:

```
FastRender.route('/view/:id', function(params) {
    this.subscribe('pub.subscribe', id);
});
```

Downgrading to 1.7.3 fixes the issue, so it seems that there is a breaking change in 1.8.2?

**Comment by StorytellerCZ** [comment]
Does 1.8.1 or 1.8.0 work?

**Comment by StorytellerCZ** [comment]
Possibly related to #165 ?

**Comment by StorytellerCZ** [comment]
@dnish can you please check v1.8.3? I think I have found the issue and fixed it there.

**Comment by wreiske** [comment]
We also upgraded to 1.8.3 and broke a ton of our subscriptions. We were seeing really odd behavior and took awhile to root cause that publish composite was the issue. Once we reverted back to  1.8.1, everything started working again.

**Comment by StorytellerCZ** [comment]
Great, now we at least have 1.8.1 as a good base to further investigate this issue.

**Comment by StorytellerCZ** [comment]
Must be something in #160

**Comment by StorytellerCZ** [comment]
@wreiske can you please check out #171 to see if that fixes your problem. It did fix it on my side.

**Comment by aboire** [comment]
@wreiske @dnish Do you have an example of code from a publish that reproduces the error to give me?

**Comment by wreiske** [comment]
> @wreiske @dnish Do you have an example of code from a publish that reproduces the error to give me?

I would need to experiment a bit, we have a very large application. One of our engineers said "it's like all the subscriptions are broken!" before we reverted back to 1.8.1.

**Comment by aboire** [comment]
@wreiske have you used fastRender too, what version of meteor are you on? is the error the same as the one mentioned in the issue?

**Comment by wreiske** [comment]
> @wreiske have you used fastRender too, what version of meteor are you on? is the error the same as the one mentioned in the issue?

Yes, we use communitypackages:fast-render@4.0.6 and we are on METEOR@2.13.3. We saw the "Doc not found in list:" a few times in the logs, but it didn't happen all the time. Possibly it was time-based and was timing out after a while and spitting out that error?

**Comment by wreiske** [comment]
![image](https://github.com/Meteor-Community-Packages/meteor-publish-composite/assets/6295044/64bf2f21-b362-4935-9cc1-5c6b9709d63e)

```
Error Doc not found in list: CahpMK8iXu2c6Az3W 
    packages/reywood:publish-composite/lib/published_document_list.js:23:13 PublishedDocumentList.addChildPub
    packages/reywood:publish-composite/lib/publication.js:93:26 
    /home/wreiske/.meteor/packages/promise/.0.12.2.mkx0xc.55d3++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 
    /home/wreiske/.meteor/packages/promise/.0.12.2.mkx0xc.55d3++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12 Function.Promise.await
    packages/reywood:publish-composite/lib/publication.js:43:11 
    /home/wreiske/.meteor/packages/promise/.0.12.2.mkx0xc.55d3++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 
    ```

**Comment by StorytellerCZ** [comment]
I think there could be potentially some await or something missing somewhere, as when i reload the page any time after the initial error things worked fine.
