### ISSUE TITLE
wrong topLevelDocument in third Level find

### ISSUE THREAD

**Issue by darkship** [Meteor-Community-Packages/meteor-publish-composite#68]
My repo : https://github.com/darkship/test_publish_composite_update_array_bug

You will see that the number of items returned in <code>ItemsThroughSecondLevelPublish</code> is not the same as in <code>ItemsThroughThirdLevelPublish</code>

**Comment by Data-Meister** [comment]
I'm having the same problem. 

It's like the third level find is getting the PREVIOUS value for topLevelDocument

**Comment by Data-Meister** [comment]
Fixed! Thanks so much Darkship for making that simple project it was really helpful. Submitting PR now.
