### ISSUE TITLE
Third level is not reactive when update top level parent

### ISSUE THREAD

**Issue by johngonzalez** [Meteor-Community-Packages/meteor-publish-composite#88]
Congratulations for the package. I have the following pattern:

``` javascript
{
    find: function() {
        // Return a cursor containing top level documents
    },
    children: [
        {
            find: function(topLevelDocument) {
                // Return a cursor of second tier documents.
            },
            children: [ // Third level
                {
                    find: function(secondTierDocument, topLevelDocument) {
                        // Return a cursor of third tier documents. 
                        // But when change some property of topLevelDocument is not reactive
                    },
                    children: [
                       // Repeat as many levels deep as you like
                    ]
                }
            ]
        },
        {
            find: function(topLevelDocument) {
                // Return another cursor of second tier documents.
            }
        }
    ]
}
```

At third level, is possible get all parent documents as secondTierDocument and topLevelDocument, but when topLevelDocument change, the result isn't update reactively in Third level. I don't know if I am losing some thing or this could a enhancement of this excellent pakage. Thanks

**Comment by Nisthar** [comment]
@johngonzalez Any solution for this?

**Comment by zimme** [comment]
Please check if this works as expected with the latest version. I believe this might be related to an issue that was fixed in that version.

**Comment by jmdsg** [comment]
I don't think this issue is solved yet, and i'm using the last version 1.7.3.

**Comment by srikant-lavu** [comment]
I'm using version 1.7.3 and having the same issue as @jmdsg 

Any update on this? or anyone found a workaround?

Thank you.

**Comment by StorytellerCZ** [comment]
Closing and continuing tracking in #146
